#!/bin/bash

sleep 1

xrandr --dpi 96

/home/stratos/stow/bin/hidpi-switch

/home/stratos/stow/bin/randomWallpapers.sh

/home/stratos/stow/bin/setupLocaleSwitching.sh

#sudo /home/stratos/stow/bin/esaConnect

i3-msg "workspace 1: www, move workspace to output DP2-2"
i3-msg "workspace 6: comms, move workspace to output DP2-3"
i3-msg "workspace 3: ide, move workspace to output DP2-2"
i3-msg "workspace 4: preview, move workspace to output DP2-2"
i3-msg "workspace 5: email, move workspace to output DP2-2"
