#!/bin/bash

sleep 1

i3-msg "workspace 1:, move workspace to output eDP1"
i3-msg "workspace 6:, move workspace to output eDP1"
i3-msg "workspace 3:, move workspace to output eDP1"
i3-msg "workspace 4:, move workspace to output eDP1"
i3-msg "workspace 5:, move workspace to output eDP1"

xrandr --dpi 144

/home/stratos/stow/bin/hidpi-switch

/home/stratos/stow/bin/randomWallpapers.sh

/home/stratos/stow/bin/setupLocaleSwitching.sh
